name: use-or-create-compute
on: 
  workflow_call:
    inputs:
      cluster_name:
        required: true
        type: string
      size:  
        required: true
        type: string
      min_instances: 
        required: true
        type: number
      max_instances: 
        required: true
        type: number
      resource_group:   
        required: true
        type: string
      workspace_name:  
        required: true
        type: string
      cluster_tier: 
        required: false
        type: string
    secrets:
      creds:
        required: true
jobs:
  use-or-create-compute:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          creds: ${{secrets.creds}}
          enable-AzPSSession: true 
      
      - name: install-extension
        run: az extension add -n ml -y
      
      - name: update-extension
        run: az extension update -n ml
      
      - name: check-compute-exists
        id: check_compute
        run: |
          EXISTS=$(az ml compute list -g ${{ inputs.resource_group }} -w ${{ inputs.workspace_name }} --query "[?name=='${{ inputs.cluster_name }}'].name" -o tsv)
          if [ -n "$EXISTS" ]; then
            echo "Compute cluster ${{ inputs.cluster_name }} exists."
            echo "compute_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Compute cluster ${{ inputs.cluster_name }} does not exist."
            echo "compute_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: use-existing-compute
        if: steps.check_compute.outputs.compute_exists == 'true'
        run: |
          echo "Using existing compute cluster ${{ inputs.cluster_name }}"
      
      - name: create-compute-default-tier
        if: steps.check_compute.outputs.compute_exists == 'false' && inputs.cluster_tier == ''
        run: |
          az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type AmlCompute \
                                  --tier "dedicated" \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
      
      - name: create-compute-using-tier
        if: steps.check_compute.outputs.compute_exists == 'false' && inputs.cluster_tier != ''
        run: |
          az ml compute create --name ${{ inputs.cluster_name }} \
                                  --type AmlCompute \
                                  --tier ${{ inputs.cluster_tier }} \
                                  --size ${{ inputs.size }} \
                                  --min-instances ${{ inputs.min_instances }} \
                                  --max-instances ${{ inputs.max_instances }} \
                                  --resource-group ${{ inputs.resource_group }} \
                                  --workspace-name ${{ inputs.workspace_name }}
